apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ell3o0mz0-nodejs 
  janus-idp.io/tekton: ell3o0mz0-nodejs
  backstage.io/kubernetes-id: ell3o0mz0-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ell3o0mz0-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml